EndpointCurler and EndpointContentCurler don't return errors
Returning the error is problematic in our case since all usages have the form:

  Eventually(IndexCounter(...)).Should(Equal(...))

Which usually fails with cryptic error message if the second return
value (i.e. the error) isn't nil.

  Error: Unexpected non-nil/non-zero extra argument at index 1:
   <*url.Error>: &url.Error{Op:"Get", URL:"http://host/index", Err:(*net.OpError)(0xabcd)}<Paste>

Similar to previous commit's fix